### ISSUE TITLE
react.jsx.TransformError？？？

### ISSUE THREAD

**Issue by qichaotang** [stitchfix/pyxley#19]
I run four examples,but it always -->react.jsx.TransformError, I can't make it,I need help!!!

**Comment by nmkridler** [comment]
Can you please outline the steps you took and your setup? If it's failing to transform the react code, you may be missing libraries.

**Comment by qichaotang** [comment]
Thanks your reply,I have made it by using Centos，before，I use the WIn10，I run four examples,but I feel uncertain.For example,while running custom_react, how to  determine x-axis，and ID isn't x-axis!

**Comment by qianqianxiao** [comment]
hi, nmkridler, I have made it by using OS X, have the same question:

/usr/bin/python /Users/yoyo/Documents/pyxley-master/examples/datamaps/project/app.py
Traceback (most recent call last):
  File "/Users/yoyo/Documents/pyxley-master/examples/datamaps/project/app.py", line 55, in <module>
    sb = ui.render_layout(app, "./static/layout.js")
  File "build/bdist.macosx-10.11-intel/egg/pyxley/ui.py", line 135, in render_layout
  File "build/bdist.macosx-10.11-intel/egg/pyxley/react_template.py", line 95, in __init__
  File "build/bdist.macosx-10.11-intel/egg/pyxley/react_template.py", line 34, in to_js
  File "/Library/Python/2.7/site-packages/react/jsx.py", line 45, in transform_string
    raise TransformError(str(e))
react.jsx.TransformError: ReferenceError: Can't find variable: global

but , before, I used win8, it was OK , I don't know why.

**Comment by BruceDone** [comment]
hi yoyo ,you may the same problem i solved yesterday ,please refer my question:
https://github.com/stitchfix/pyxley/issues/24
