### ISSUE TITLE
Import ui error

### ISSUE THREAD

**Issue by springcoil** [stitchfix/pyxley#3]
Hi I get the following errors. 
Traceback (most recent call last):
  File "app.py", line 13, in <module>
    from pyxley.charts.datatables import DataTable
  File "/Users/peadarcoyle/anaconda/lib/python3.4/site-packages/pyxley/__init__.py", line 1, in <module>
    import ui
ImportError: No module named 'ui'
Any suggestions on why this might be?

**Comment by springcoil** [comment]
This is resolved now with the fix of Python 3.4
