### ISSUE TITLE
Error instaling node-sass when using pyxapp --init . (ubuntu 14.04)

### ISSUE THREAD

**Issue by gcastorena** [stitchfix/pyxley#41]
Hi, I am starting to learn your package and I was trying the example of metricsgraphics. 

Installed npm globally, python packages are run in virtualenv (pyenv) with python 2.7, also flask and pyxley are only installed in virtual environment. 

The error I get is:

 node-sass@3.7.0 install /home/platino/pyceley/pyxley-master/examples/metricsgraphics/node_modules/node-sass
> node scripts/install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 127
npm ERR! not ok code 0
Traceback (most recent call last):
  File "/home/platino/.pyenv/versions/webdashapp/bin/pyxapp", line 24, in <module>
    do_init(args)
  File "/home/platino/.pyenv/versions/webdashapp/bin/pyxapp", line 20, in do_init
    npm.run()
  File "/home/platino/.pyenv/versions/2.7.6/envs/webdashapp/lib/python2.7/site-packages/pyxley/utils/npm.py", line 93, in run
    run(cmds, cwd=self.repo_root)
  File "/home/platino/.pyenv/versions/2.7.6/envs/webdashapp/lib/python2.7/site-packages/pyxley/utils/npm.py", line 13, in run
    return check_call(cmd, *args, **kwargs)
  File "/home/platino/.pyenv/versions/2.7.6/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['npm', 'install', '--progress-false']' returned non-zero exit status 1

Is it I am messing with the environments?  Thanks a lot

**Comment by gcastorena** [comment]
Sorry, I 've found the issue, it as only a matter of installing nodejs-legacy
http://stackoverflow.com/questions/35468353/installing-ionic-on-linux-errs
Thanks
